name:         text-slides
version:      0.1
synopsis:     Generate slides from markdown
description:
    text-slides generates slides in various formats from a markdown
    description. It offers supports for diagrams, importing drawings
    from keynote and for source code extraction.
license:      BSD3
author:       Stefan Wehr
maintainer:   Stefan Wehr
github:       skogsbaer/text-slides
category:     Development
extra-source-files:
  - LICENSE
  - README.md
data-files: data/*

library:
  source-dirs: src
  dependencies:
    - aeson
    - QuickCheck
    - base
    - base16-bytestring
    - bytestring
    - containers
    - cryptohash-md5
    - directory
    - exceptions
    - extra
    - filepath
    - language-java
    - megaparsec
    - optparse-applicative
    - parsec
    - process
    - process-extras
    - safe
    - shake
    - shell-escape
    - temporary
    - text
    - time
    - transformers
    - unordered-containers
    - unix
    - vector
    - yaml
  ghc-options:
    - -Werror -W -fwarn-unused-imports -fwarn-unused-binds -fwarn-orphans
    - -fwarn-unused-matches -fwarn-unused-do-bind -fwarn-wrong-do-bind
    - -fwarn-missing-signatures -fno-warn-partial-type-signatures
    - -Wredundant-constraints -fwarn-incomplete-patterns

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - base
    - text-slides
  ghc-options:
    - -Werror -W -fwarn-unused-imports -fwarn-unused-binds -fwarn-orphans
    - -fwarn-unused-matches -fwarn-unused-do-bind -fwarn-wrong-do-bind
    - -fwarn-missing-signatures -fno-warn-partial-type-signatures
    - -Wredundant-constraints -fwarn-incomplete-patterns -rtsopts

tests:
  unit-tests:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - aeson
      - base
      - bytestring
      - containers
      - directory
      - extra
      - filepath
      - heredoc
      - HTF
      - language-java
      - process
      - safe
      - temporary
      - text-slides
      - text
      - transformers
      - vector
    build-tools: HTF
    ghc-options:
      - -Werror -W -fwarn-unused-imports -fwarn-unused-binds -fwarn-orphans
      - -fwarn-unused-matches -fwarn-unused-do-bind -fwarn-wrong-do-bind
      - -fwarn-missing-signatures -fno-warn-partial-type-signatures
      - -Wredundant-constraints -fwarn-incomplete-patterns -rtsopts


default-extensions:
  - DeriveDataTypeable
  - DeriveFoldable
  - DeriveFunctor
  - DeriveGeneric
  - DeriveTraversable
  - DerivingStrategies
  - DoAndIfThenElse
  - EmptyDataDecls
  - FlexibleContexts
  - OverloadedStrings
  - ScopedTypeVariables
  - StandaloneDeriving
  - TypeOperators
  - ViewPatterns
