resolver: lts-16.31
# resolver: nightly-2022-09-26
packages:
- .
extra-deps:
  #- git: https://github.com/skogsbaer/language-java.git
  - git: /Users/swehr/devel/language-java
    commit: 2c58680189f50c3117537bd90b302236b36c5874
